Capstone implementation
flemton/capstone1 pull request #1
Opened 2023-01-04 19:09 UTC by flemton

### Dear reviewer, it is my pleasure to request a review for my PR.
### Below were the changes implemented

- Add navigations for Mobile and Desktop
- Add Menu button and Close Button
- Add Headline Section
- Add Main program Section
- Add Speakers section dynamically with JavaScript
- Update READme file
- Deployed Project
__Any needed corrections and suggestions are welcome__
**Cheers 🥂**

2023-01-04 20:49 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @flemton, 

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif?cid=ecf05e47n6s5huda7qh40syoppcaspe9vx68ddmxerd08owm&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

- [ ] You should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:

  - A description of the project.
  - A demo of the project features (different pages and different screen sizes).
  - You should also highlight some interesting piece of code or something you built that you are very proud of.

  For recording the video you can use tools like [Loom](https://www.loom.com/) that let you share a private link to the recording, and configure a shot that shows your computer screen and your face at the same time in a small picture.

  Kindly add the video link to your pull request description.

- [x] Please know that you have a lot of `alt` attributes that are empty, please fill something there, I couldn't point them on the code because there are a lot, just search for them one by one using the editor and fill them in!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 20:49 UTC, mirouhml commented on README.md
- [x] Kindly add the correct acknowledgment for the designer [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), you only mentioned Creative Summons, which is wrong, Creative Summons is a license. 😄

2023-01-04 20:49 UTC, mirouhml commented on style.css
> +}
- [x] Please know that the menu's background should be either transparent or has the same color/pattern as the top section background, kindly adjust this. 😌

2023-01-04 20:49 UTC, mirouhml commented on index.html
> +            </div>
- [x] Please know that this is a navigation menu as well, kindly use the correct tag, which is `nav`. 😁

2023-01-04 20:49 UTC, mirouhml commented on style.css
> +}
- [x] Kindly use the correct font family here which is `COCOGOOSE`. 😄

2023-01-04 20:49 UTC, mirouhml commented on style.css
> +}
- [x] Kindly use the correct font family here as well, which is `COCOGOOSE`. 😄

2023-01-04 20:49 UTC, mirouhml commented on style.css
> +}
- [x] Kindly use the correct font-family `Lato` for all your navigation menus, you shouldn't use a font that isn't mentioned in the design, if you add it to your `body`, as I will point later it will fix your issue. 🙂

2023-01-04 20:49 UTC, mirouhml commented on style.css
> +}
- [x] Please know that the copyright section on the about page should be dark colored, and this change should only happen on the desktop version not mobile, for mobile it's correct. 😄

2023-01-04 20:49 UTC, mirouhml commented on about.html
> +        </section>
- [x] Please know that you should hide this section on desktop, and only show it on the mobile version. 😄

2023-01-04 20:49 UTC, mirouhml commented on style.css
> +}
- [x] Kindly fix the margin of this section, this is how it looks on your website 🙂: 

  ![image](https://user-images.githubusercontent.com/20567503/210641963-d789930e-fdae-44f3-a32e-db314e171cc8.png)

  And this is how it looks on the original design:
  
  ![image](https://user-images.githubusercontent.com/20567503/210642036-51b5e2c7-f9d8-48cc-94fe-4b24ef6225f3.png)

- [x] Also the logos don't look good because you fixed the `width` without adjusting the `height`, I recommend you add `fit-content` for the `height` so they look like their original size, then add `align-items: center;` to `.partners div` to center them vertically, this is how they'll look after that:

  ![image](https://user-images.githubusercontent.com/20567503/210643093-b08c26d6-e902-4026-9675-417cc958e008.png)
  
  And this is how they looked before:
  
  
  ![image](https://user-images.githubusercontent.com/20567503/210643207-833552e8-4966-4373-8945-a21007398dad.png)

  They are a bit stretched, kindly fix them as I showed you. 😄

2023-01-04 20:49 UTC, mirouhml commented on about.html
> +        </h3>
- [x] Please know that the About Logo and the title of the section on mobile are overlapping kindly fix the issue 🙂, this is how it looks:

  ![image](https://user-images.githubusercontent.com/20567503/210643489-31a1a612-30cc-4581-96b2-d8681720b73e.png)

2023-01-04 20:49 UTC, mirouhml commented on index.html
> +        -->
- [x] Please know that you shouldn't leave any comments when trying to merge the final version to the master branch, kindly remove any commented section you have. 😄

2023-01-04 20:49 UTC, mirouhml commented on style.css
> +}
- [x] Please know that on large screens the speakers will be displayed in 3 columns instead of 2, this is how it looks on my end:

  ![image](https://user-images.githubusercontent.com/20567503/210644451-1795405b-835e-4447-89e3-dbc40318b77b.png)

  I recommend that you use `grid` to fix the columns to 2 instead of using `flexbox`. 😄

2023-01-04 20:49 UTC, mirouhml commented on style.css
> +}
- [x] I recommend that you add `font-family: Lato;` here as this will mean the whole website will use the `Lato` font and then later you can specify where to use `COCOGOOSE`, because I noticed that you have a lot of text that is using `Times New Roman` instead which will ruin the design for you, kindly add this. 😁

2023-01-04 20:49 UTC, mirouhml commented on style.css
> +}
- [x] Kindly add some margin as there is not much space between the previous section and the title of this section, this is how it looks:

  ![image](https://user-images.githubusercontent.com/20567503/210645703-65faefe1-3a27-424a-a145-6b3928163f2a.png)

  Kindly fix this for both mobile and desktop. 😁

2023-01-04 20:49 UTC, mirouhml commented on index.html
> +        </a>
- [x] Please know that if you go from mobile to desktop the hamburger icon doesn't disappear, this is how it looks:

  ![image](https://user-images.githubusercontent.com/20567503/210645911-b5b35e52-b6bf-494b-ae34-f2d2f55c0f6e.png)

  Kindly fix this issue for both pages. 🙂

2023-01-04 20:49 UTC, mirouhml commented on index.html
> +            <span class="speaker">
- [x] Please know that for this section on mobile, you should display only two speakers and then add a "MORE" button to show the rest when clicked, this is how it looks on the original design:

  ![image](https://user-images.githubusercontent.com/20567503/210646561-53d0d941-e6de-4879-8e98-2c566e090183.png)

  Kindly implement this! 😌

2023-01-05 15:27 UTC, frank1738 approved these changes
Hi @flemton , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/fDbzXb6Cv5L56/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 15:56 UTC, merged